example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import show_xml_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import *

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', wishlist_ajax, name='wishlist_ajax'),
    path('ajax/submit/', submit_ajax, name='submit_ajax')
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

wishlist/forms.py
from django import forms
from django.forms import Form, ModelForm
from wishlist.models import BarangWishlist

class ItemForm(ModelForm):
    deskripsi = forms.CharField(max_length=200)
    class Meta:
        model = BarangWishlist
        fields = ['nama_barang', 'harga_barang', 'deskripsi']

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from wishlist.forms import ItemForm

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Ravena Meilani',
    'NPM': '2106631923',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

def wishlist_ajax(request):
    context = {
    'last_login': request.COOKIES['last_login'],
    'form': 'ItemForm',
    }
    return render(request, "wishlist_ajax.html", context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse (serializers.serialize("xml", data), content_type="application/xml")
def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")
def show_xml_by_id (request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")
def show_json_by_id (request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

data_barang_wishlist = BarangWishlist.objects.all()
context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Ravena Meilani',
    'NPM': '2106631923'
}

def submit_ajax(request):
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            item = BarangWishlist()
            item.nama_barang = form.data['nama_barang']
            item.harga_barang = form.data['harga_barang']
            item.deskripsi = form.data['deskripsi']
            item.save()

    response = HttpResponseRedirect(reverse("wishlist:wishlist_ajax")) 
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body class="mx-5 p-5">
  {% block content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/navbar.html
<div class="navbar bg-info shadow">
    <div class="container-fluid">
        <div class="d-flex w-100 justify-content-between">
            <span class="navbar-brand align-self-center">Wishlist</span>
            <div class="d-flex gap-4">
                <p class="align-self-center m-0">{{nama}}</p>
                <button class="border rounded border-info">
                    <a href="{% url 'wishlist:logout' %}" class="text-decoration-none">Logout</a>
                </button>
            </div>
        </div>
    </div>
</div>

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="p-4">
    <h5>Nama: <b>{{nama}}</b></h5>
    <h5>NPM: <b>{{NPM}}</b></h5>
    <br>
    <br>
    <table class="table table-bordered">
        <tr>
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
        </tr>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        {% for barang in list_barang %}
        <tr>
            <th>{{barang.nama_barang}}</th>
            <th>{{barang.harga_barang}}</th>
            <th>{{barang.deskripsi}}</th>
        </tr>
    {% endfor %}
    </table>

<h5>Sesi terakhir login: {{ last_login }}</h5>

<button><a href="{% url 'wishlist:logout' %}">Logout</a></button>


{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
{% endblock meta %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script type="text/javascript">
        $(document).ready(function(){
            $.getJSON("{% url 'wishlist:show_json' %}") , function(data){
                item = '';
                $.each(data, function (key, value) {
                    item += '<tr>';
                    item += '<td>' + 
                        value.fields.nama_barang + '</td>';
                    item += '<td>' + 
                        value.fields.harga_barang + '</td>';
                    item += '<td>' + 
                        value.fields.deskripsi + '</td>';
                    item += '</tr>';
                });
                $('#data').append(item);
            });
            $(function() {
                $.ajaxSetup({
                    headers: {
                      "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
                    }
                })
             });
             $("#submit").click(function(){
                alert("submitting!");
                $.post("{% url 'wishlist:submit_ajax' %}", $('#item_data').serialize(), function(){
                    $(location).attr('href', "{% url 'wishlist:wishlist_ajax' %}");
                });
            });
            $("#new-item").click(function(){
                $(location).attr('href',"{% url 'wishlist:submit_ajax' %}");
            });
            $("#bonus").click(function() {
                if(typeof(Storage) !== "undefined") {
                    if (localStorage.clickcount) {
                        localStorage.clickcount = Number(localStorage.clickcount)+1;
                    } else {
                        localStorage.clickcount = 1;
                    }
                    document.getElementById("result").innerHTML = "You have clicked the button " + localStorage.clickcount + " time(s).";
                } else {
                    document.getElementById("result").innerHTML = "Sorry, your browser does not support web storage...";
                }
            });
        });
        </script>
{% include 'navbar.html' %}

<div class="p-4">
    <h5>Nama: {{nama}} </h5>
    <b>{{nama}}</b>
    <br>
    <br>
    <br>
    <table class="table table-bordered" id="1">
        <tr>
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
        </tr>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        {% for barang in list_barang %}
        <tr>
            <th>{{barang.nama_barang}}</th>
            <th>{{barang.harga_barang}}</th>
            <th>{{barang.deskripsi}}</th>
        </tr>
    {% endfor %}
    </table>

<h5>Sesi terakhir login: {{ last_login }}</h5>

<button><a href="{% url 'wishlist:logout' %}">Logout</a></button>


{% endblock content %}